### ISSUE TITLE
Getting ArgumentNullException: 'filename' cannot be null with spring proxied methods

### ISSUE THREAD

**Issue by fabn** [rollbar/rollbar-java#50]
I've integrated rollbar into a spring project and I'm using it to log errors that happens in `@Async` methods with this code:

```java
    @Override
    public AsyncUncaughtExceptionHandler getAsyncUncaughtExceptionHandler() {
        return (ex, method, params) -> {
            String message = String.format("Error in async task of type %s:%s", method.getDeclaringClass(), method.getName());
            log.error("My Error while executing async method: {}", method.getName(), ex);
            rollbar.error(ex, message);
        };
    }
```

However the above code raises this rollbar error:

```
com.rollbar.utilities.ArgumentNullException: 'filename' cannot be null
	at com.rollbar.utilities.Validate.isNotNullOrWhitespace(Validate.java:20) ~[rollbar-utilities-0.5.4.jar:0.5.4]
	at com.rollbar.payload.data.body.Frame.<init>(Frame.java:65) ~[rollbar-payload-0.5.4.jar:0.5.4]
	at com.rollbar.payload.data.body.Frame.fromStackTraceElement(Frame.java:106) ~[rollbar-payload-0.5.4.jar:0.5.4]
	at com.rollbar.payload.data.body.Frame.fromThrowable(Frame.java:88) ~[rollbar-payload-0.5.4.jar:0.5.4]
	at com.rollbar.payload.data.body.Trace.fromThrowable(Trace.java:50) ~[rollbar-payload-0.5.4.jar:0.5.4]
	at com.rollbar.payload.data.body.Body.trace(Body.java:61) ~[rollbar-payload-0.5.4.jar:0.5.4]
	at com.rollbar.payload.data.body.Body.fromError(Body.java:49) ~[rollbar-payload-0.5.4.jar:0.5.4]
	at com.rollbar.Rollbar.buildPayload(Rollbar.java:517) ~[rollbar-0.5.4.jar:0.5.4]
	at com.rollbar.Rollbar.log(Rollbar.java:510) ~[rollbar-0.5.4.jar:0.5.4]
	at com.rollbar.Rollbar.error(Rollbar.java:266) ~[rollbar-0.5.4.jar:0.5.4]
```

**Comment by rokob** [comment]
Fixed in https://github.com/rollbar/rollbar-java/pull/51
